/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ActionsSecretAccess.
func (mg *ActionsSecretAccess) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this DependabotSecretAccess.
func (mg *DependabotSecretAccess) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this Membership.
func (mg *Membership) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Membership.
func (mg *Membership) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Membership.
func (mg *Membership) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Membership.
func (mg *Membership) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Membership.
func (mg *Membership) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Membership.
func (mg *Membership) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Membership.
func (mg *Membership) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Membership.
func (mg *Membership) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Membership.
func (mg *Membership) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Membership.
func (mg *Membership) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this Organization.
func (mg *Organization) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Organization.
func (mg *Organization) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Organization.
func (mg *Organization) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Organization.
func (mg *Organization) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Organization.
func (mg *Organization) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Organization.
func (mg *Organization) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Organization.
func (mg *Organization) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Organization.
func (mg *Organization) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Organization.
func (mg *Organization) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Organization.
func (mg *Organization) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this OrganizationVariable.
func (mg *OrganizationVariable) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this OrganizationVariable.
func (mg *OrganizationVariable) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this OrganizationVariable.
func (mg *OrganizationVariable) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this OrganizationVariable.
func (mg *OrganizationVariable) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this OrganizationVariable.
func (mg *OrganizationVariable) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this OrganizationVariable.
func (mg *OrganizationVariable) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this OrganizationVariable.
func (mg *OrganizationVariable) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this OrganizationVariable.
func (mg *OrganizationVariable) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this OrganizationVariable.
func (mg *OrganizationVariable) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this OrganizationVariable.
func (mg *OrganizationVariable) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this OrganizationWebhook.
func (mg *OrganizationWebhook) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this OrganizationWebhook.
func (mg *OrganizationWebhook) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this OrganizationWebhook.
func (mg *OrganizationWebhook) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this OrganizationWebhook.
func (mg *OrganizationWebhook) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this OrganizationWebhook.
func (mg *OrganizationWebhook) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this OrganizationWebhook.
func (mg *OrganizationWebhook) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this OrganizationWebhook.
func (mg *OrganizationWebhook) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this OrganizationWebhook.
func (mg *OrganizationWebhook) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this OrganizationWebhook.
func (mg *OrganizationWebhook) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this OrganizationWebhook.
func (mg *OrganizationWebhook) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this Repository.
func (mg *Repository) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Repository.
func (mg *Repository) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Repository.
func (mg *Repository) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Repository.
func (mg *Repository) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Repository.
func (mg *Repository) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Repository.
func (mg *Repository) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Repository.
func (mg *Repository) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Repository.
func (mg *Repository) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Repository.
func (mg *Repository) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Repository.
func (mg *Repository) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this RunnerGroup.
func (mg *RunnerGroup) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this RunnerGroup.
func (mg *RunnerGroup) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this RunnerGroup.
func (mg *RunnerGroup) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this RunnerGroup.
func (mg *RunnerGroup) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this RunnerGroup.
func (mg *RunnerGroup) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this RunnerGroup.
func (mg *RunnerGroup) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this RunnerGroup.
func (mg *RunnerGroup) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this RunnerGroup.
func (mg *RunnerGroup) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this RunnerGroup.
func (mg *RunnerGroup) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this RunnerGroup.
func (mg *RunnerGroup) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this Team.
func (mg *Team) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Team.
func (mg *Team) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Team.
func (mg *Team) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Team.
func (mg *Team) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Team.
func (mg *Team) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Team.
func (mg *Team) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Team.
func (mg *Team) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Team.
func (mg *Team) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Team.
func (mg *Team) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Team.
func (mg *Team) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
