// Code generated by generate-registration. DO NOT EDIT.

package controller

import (
	"time"

	"k8s.io/apimachinery/pkg/runtime/schema"
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"

	clusterorganizationsv1alpha1 "github.com/crossplane/provider-github/apis/cluster/organizations/v1alpha1"
	namespacedorganizationsv1alpha1 "github.com/crossplane/provider-github/apis/namespaced/organizations/v1alpha1"
	"github.com/crossplane/provider-github/internal/controller/actionssecretaccess"
	"github.com/crossplane/provider-github/internal/controller/config"
	"github.com/crossplane/provider-github/internal/controller/dependabotsecretaccess"
	"github.com/crossplane/provider-github/internal/controller/membership"
	"github.com/crossplane/provider-github/internal/controller/organization"
	"github.com/crossplane/provider-github/internal/controller/organizationvariable"
	"github.com/crossplane/provider-github/internal/controller/organizationwebhook"
	"github.com/crossplane/provider-github/internal/controller/repository"
	"github.com/crossplane/provider-github/internal/controller/runnergroup"
	"github.com/crossplane/provider-github/internal/controller/team"
	"github.com/crossplane/provider-github/internal/telemetry"
)

// setupFunc wires one controller into the manager.
type setupFunc func(ctrl.Manager, controller.Options, *telemetry.RateLimitMetrics, time.Duration) error

// Setup creates all GitHub controllers eagerly and adds them to the supplied manager.
// A reconcileTimeout of zero or less leaves the reconciler's default in place.
func Setup(mgr ctrl.Manager, o controller.Options, metrics *telemetry.RateLimitMetrics, reconcileTimeout time.Duration) error {
	if err := config.Setup(mgr, o, metrics); err != nil {
		return err
	}
	for _, setup := range []setupFunc{
		actionssecretaccess.SetupWithTimeout,
		dependabotsecretaccess.SetupWithTimeout,
		membership.SetupWithTimeout,
		organization.SetupWithTimeout,
		organizationvariable.SetupWithTimeout,
		organizationwebhook.SetupWithTimeout,
		repository.SetupWithTimeout,
		runnergroup.SetupWithTimeout,
		team.SetupWithTimeout,
		actionssecretaccess.SetupNamespacedWithTimeout,
		dependabotsecretaccess.SetupNamespacedWithTimeout,
		membership.SetupNamespacedWithTimeout,
		organization.SetupNamespacedWithTimeout,
		organizationvariable.SetupNamespacedWithTimeout,
		organizationwebhook.SetupNamespacedWithTimeout,
		repository.SetupNamespacedWithTimeout,
		runnergroup.SetupNamespacedWithTimeout,
		team.SetupNamespacedWithTimeout,
	} {
		if err := setup(mgr, o, metrics, reconcileTimeout); err != nil {
			return err
		}
	}
	return nil
}

// SetupGated creates the ProviderConfig controllers eagerly and defers every
// managed resource controller until the CustomResourceDefinition of its scope
// variant is installed and established.
func SetupGated(mgr ctrl.Manager, o controller.Options, metrics *telemetry.RateLimitMetrics, reconcileTimeout time.Duration) error {
	if err := config.Setup(mgr, o, metrics); err != nil {
		return err
	}
	for _, g := range []struct {
		gvk   schema.GroupVersionKind
		setup setupFunc
	}{
		{clusterorganizationsv1alpha1.ActionsSecretAccessGroupVersionKind, actionssecretaccess.SetupWithTimeout},
		{clusterorganizationsv1alpha1.DependabotSecretAccessGroupVersionKind, dependabotsecretaccess.SetupWithTimeout},
		{clusterorganizationsv1alpha1.MembershipGroupVersionKind, membership.SetupWithTimeout},
		{clusterorganizationsv1alpha1.OrganizationGroupVersionKind, organization.SetupWithTimeout},
		{clusterorganizationsv1alpha1.OrganizationVariableGroupVersionKind, organizationvariable.SetupWithTimeout},
		{clusterorganizationsv1alpha1.OrganizationWebhookGroupVersionKind, organizationwebhook.SetupWithTimeout},
		{clusterorganizationsv1alpha1.RepositoryGroupVersionKind, repository.SetupWithTimeout},
		{clusterorganizationsv1alpha1.RunnerGroupGroupVersionKind, runnergroup.SetupWithTimeout},
		{clusterorganizationsv1alpha1.TeamGroupVersionKind, team.SetupWithTimeout},
		{namespacedorganizationsv1alpha1.ActionsSecretAccessGroupVersionKind, actionssecretaccess.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.DependabotSecretAccessGroupVersionKind, dependabotsecretaccess.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.MembershipGroupVersionKind, membership.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.OrganizationGroupVersionKind, organization.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.OrganizationVariableGroupVersionKind, organizationvariable.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.OrganizationWebhookGroupVersionKind, organizationwebhook.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.RepositoryGroupVersionKind, repository.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.RunnerGroupGroupVersionKind, runnergroup.SetupNamespacedWithTimeout},
		{namespacedorganizationsv1alpha1.TeamGroupVersionKind, team.SetupNamespacedWithTimeout},
	} {
		// Each iteration needs its own copy: the callback runs later.
		gvk, setup := g.gvk, g.setup
		o.Gate.Register(func() {
			if err := setup(mgr, o, metrics, reconcileTimeout); err != nil {
				o.Logger.Info("Cannot setup gated controller", "gvk", gvk.String(), "error", err.Error())
			}
		}, gvk)
	}
	return nil
}
