//go:build ignore

/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// generate-registration scans the provider's directory structure and writes
// the two registration files:
//
//	apis/zz_generated_register.go             scheme registration
//	internal/controller/zz_generated_register.go  controller registration
//
// Usage: go run hack/generate-registration.go <module path>
//
// Scheme registration: every version directory that holds a
// groupversion_info.go under apis/cluster/ or apis/namespaced/ is registered,
// both the core package (the ProviderConfig types) and each API group package
// (the managed resources).
//
// Controller registration: a directory internal/controller/<kind>/ is
// registered when apis/cluster/<group>/<version>/<kind>_types.go and
// apis/namespaced/<group>/<version>/<kind>_types.go both exist. Each package
// exposes SetupWithTimeout (cluster scope) and SetupNamespacedWithTimeout
// (namespaced scope); the generated SetupGated registers each scope's
// controller on the CRD gate for that scope's GroupVersionKind. The config
// package (ProviderConfig controllers) is never gated.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const header = "// Code generated by generate-registration. DO NOT EDIT.\n\n"

var scopes = []string{"cluster", "namespaced"}

// apiPackage is a version directory holding a groupversion_info.go.
type apiPackage struct {
	scope      string
	dir        string // relative to the repository root, slash separated
	alias      string
	importPath string
}

// controllerPkg is one internal/controller/<name> package.
type controllerPkg struct {
	name       string
	clusterGVK string // qualified expression, e.g. clusterorganizationsv1alpha1.TeamGroupVersionKind
	nsGVK      string
}

func main() {
	if len(os.Args) != 2 {
		fatal("usage: go run hack/generate-registration.go <module path>")
	}
	module := os.Args[1]

	pkgs, err := scanAPIs(module)
	check(err)
	check(writeAPIs(pkgs))

	ctrls, err := scanControllers(pkgs)
	check(err)
	check(writeControllers(module, pkgs, ctrls))
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "generate-registration:", msg)
	os.Exit(1)
}

func check(err error) {
	if err != nil {
		fatal(err.Error())
	}
}

var versionDir = regexp.MustCompile(`^v[0-9]+((alpha|beta)[0-9]+)?$`)

func scanAPIs(module string) ([]apiPackage, error) {
	var out []apiPackage
	for _, scope := range scopes {
		root := filepath.Join("apis", scope)
		err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || d.Name() != "groupversion_info.go" {
				return nil
			}
			dir := filepath.ToSlash(filepath.Dir(p))
			parts := strings.Split(dir, "/")
			if !versionDir.MatchString(parts[len(parts)-1]) {
				return nil
			}
			out = append(out, apiPackage{
				scope:      scope,
				dir:        dir,
				alias:      strings.Join(parts[1:], ""),
				importPath: module + "/" + dir,
			})
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].dir < out[j].dir })
	return out, nil
}

func writeAPIs(pkgs []apiPackage) error {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("// Package apis contains Kubernetes API for the GitHub provider.\n")
	b.WriteString("package apis\n\nimport (\n\t\"k8s.io/apimachinery/pkg/runtime\"\n\n")
	for _, p := range pkgs {
		fmt.Fprintf(&b, "\t%s %q\n", p.alias, p.importPath)
	}
	b.WriteString(")\n\n")
	b.WriteString("// AddToSchemes may be used to add all resources defined in the project to a Scheme.\n")
	b.WriteString("var AddToSchemes runtime.SchemeBuilder\n\n")
	b.WriteString("// AddToScheme adds all Resources to the Scheme.\n")
	b.WriteString("func AddToScheme(s *runtime.Scheme) error {\n\treturn AddToSchemes.AddToScheme(s)\n}\n\n")
	b.WriteString("func init() {\n\t// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back.\n\tAddToSchemes = append(AddToSchemes,\n")
	for _, p := range pkgs {
		fmt.Fprintf(&b, "\t\t%s.SchemeBuilder.AddToScheme,\n", p.alias)
	}
	b.WriteString("\t)\n}\n")
	return writeGo(filepath.Join("apis", "zz_generated_register.go"), b.Bytes())
}

func scanControllers(pkgs []apiPackage) ([]controllerPkg, error) {
	entries, err := os.ReadDir(filepath.Join("internal", "controller"))
	if err != nil {
		return nil, err
	}
	var out []controllerPkg
	for _, e := range entries {
		if !e.IsDir() || e.Name() == "config" {
			continue
		}
		name := e.Name()
		c := controllerPkg{name: name}
		for _, p := range pkgs {
			gvk, ok, err := findGVK(p, name)
			if err != nil {
				return nil, err
			}
			if !ok {
				continue
			}
			if p.scope == "cluster" {
				c.clusterGVK = gvk
			} else {
				c.nsGVK = gvk
			}
		}
		if c.clusterGVK == "" || c.nsGVK == "" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out, nil
}

// findGVK returns the qualified <Kind>GroupVersionKind expression when package
// p holds <name>_types.go.
func findGVK(p apiPackage, name string) (string, bool, error) {
	b, err := os.ReadFile(filepath.FromSlash(path.Join(p.dir, name+"_types.go")))
	if os.IsNotExist(err) {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	re := regexp.MustCompile(`(?m)^\s*(\w+)GroupVersionKind\s*=`)
	for _, m := range re.FindAllStringSubmatch(string(b), -1) {
		if strings.EqualFold(m[1], name) {
			return p.alias + "." + m[1] + "GroupVersionKind", true, nil
		}
	}
	return "", false, fmt.Errorf("%s_types.go in %s declares no %sGroupVersionKind", name, p.dir, name)
}

func writeControllers(module string, pkgs []apiPackage, ctrls []controllerPkg) error {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("package controller\n\nimport (\n\t\"time\"\n\n")
	b.WriteString("\t\"k8s.io/apimachinery/pkg/runtime/schema\"\n\tctrl \"sigs.k8s.io/controller-runtime\"\n\n")
	b.WriteString("\t\"github.com/crossplane/crossplane-runtime/v2/pkg/controller\"\n\n")
	// Only the API packages some controller refers to are imported.
	used := map[string]bool{}
	for _, c := range ctrls {
		used[strings.SplitN(c.clusterGVK, ".", 2)[0]] = true
		used[strings.SplitN(c.nsGVK, ".", 2)[0]] = true
	}
	for _, p := range pkgs {
		if used[p.alias] {
			fmt.Fprintf(&b, "\t%s %q\n", p.alias, p.importPath)
		}
	}
	fmt.Fprintf(&b, "\t%q\n", module+"/internal/controller/config")
	for _, c := range ctrls {
		fmt.Fprintf(&b, "\t%q\n", module+"/internal/controller/"+c.name)
	}
	fmt.Fprintf(&b, "\t%q\n", module+"/internal/telemetry")
	b.WriteString(")\n\n")

	b.WriteString("// setupFunc wires one controller into the manager.\n")
	b.WriteString("type setupFunc func(ctrl.Manager, controller.Options, *telemetry.RateLimitMetrics, time.Duration) error\n\n")

	b.WriteString("// Setup creates all GitHub controllers eagerly and adds them to the supplied manager.\n")
	b.WriteString("// A reconcileTimeout of zero or less leaves the reconciler's default in place.\n")
	b.WriteString("func Setup(mgr ctrl.Manager, o controller.Options, metrics *telemetry.RateLimitMetrics, reconcileTimeout time.Duration) error {\n")
	b.WriteString("\tif err := config.Setup(mgr, o, metrics); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tfor _, setup := range []setupFunc{\n")
	for _, c := range ctrls {
		fmt.Fprintf(&b, "\t\t%s.SetupWithTimeout,\n", c.name)
	}
	for _, c := range ctrls {
		fmt.Fprintf(&b, "\t\t%s.SetupNamespacedWithTimeout,\n", c.name)
	}
	b.WriteString("\t} {\n\t\tif err := setup(mgr, o, metrics, reconcileTimeout); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n\treturn nil\n}\n\n")

	b.WriteString("// SetupGated creates the ProviderConfig controllers eagerly and defers every\n")
	b.WriteString("// managed resource controller until the CustomResourceDefinition of its scope\n")
	b.WriteString("// variant is installed and established.\n")
	b.WriteString("func SetupGated(mgr ctrl.Manager, o controller.Options, metrics *telemetry.RateLimitMetrics, reconcileTimeout time.Duration) error {\n")
	b.WriteString("\tif err := config.Setup(mgr, o, metrics); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tfor _, g := range []struct {\n\t\tgvk   schema.GroupVersionKind\n\t\tsetup setupFunc\n\t}{\n")
	for _, c := range ctrls {
		fmt.Fprintf(&b, "\t\t{%s, %s.SetupWithTimeout},\n", c.clusterGVK, c.name)
	}
	for _, c := range ctrls {
		fmt.Fprintf(&b, "\t\t{%s, %s.SetupNamespacedWithTimeout},\n", c.nsGVK, c.name)
	}
	b.WriteString("\t} {\n")
	b.WriteString("\t\t// Each iteration needs its own copy: the callback runs later.\n")
	b.WriteString("\t\tgvk, setup := g.gvk, g.setup\n")
	b.WriteString("\t\to.Gate.Register(func() {\n")
	b.WriteString("\t\t\tif err := setup(mgr, o, metrics, reconcileTimeout); err != nil {\n")
	b.WriteString("\t\t\t\to.Logger.Info(\"Cannot setup gated controller\", \"gvk\", gvk.String(), \"error\", err.Error())\n")
	b.WriteString("\t\t\t}\n\t\t}, gvk)\n\t}\n\treturn nil\n}\n")
	return writeGo(filepath.Join("internal", "controller", "zz_generated_register.go"), b.Bytes())
}

func writeGo(file string, src []byte) error {
	out, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("formatting %s: %w\n%s", file, err, src)
	}
	return os.WriteFile(file, out, 0o644)
}
