// Code generated by generate-registration. DO NOT EDIT.

// Package apis contains Kubernetes API for the GitHub provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	clusterorganizationsv1alpha1 "github.com/crossplane/provider-github/apis/cluster/organizations/v1alpha1"
	clusterv1alpha1 "github.com/crossplane/provider-github/apis/cluster/v1alpha1"
	namespacedorganizationsv1alpha1 "github.com/crossplane/provider-github/apis/namespaced/organizations/v1alpha1"
	namespacedv1alpha1 "github.com/crossplane/provider-github/apis/namespaced/v1alpha1"
)

// AddToSchemes may be used to add all resources defined in the project to a Scheme.
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme.
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back.
	AddToSchemes = append(AddToSchemes,
		clusterorganizationsv1alpha1.SchemeBuilder.AddToScheme,
		clusterv1alpha1.SchemeBuilder.AddToScheme,
		namespacedorganizationsv1alpha1.SchemeBuilder.AddToScheme,
		namespacedv1alpha1.SchemeBuilder.AddToScheme,
	)
}
