---
# Repository access for an existing Dependabot secret, limited to selected repositories.
# The secret must already exist on GitHub with visibility "selected".
apiVersion: organizations.github.m.crossplane.io/v1alpha1
kind: DependabotSecretAccess
metadata:
  name: sample-dependabot-secret-selected-ns
  namespace: default
  annotations:
    crossplane.io/external-name: SAMPLE_DEPENDABOT_SECRET_SELECTED-ns
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: example
  forProvider:
    orgRef:
      name: pgh-sample-organization-ns
    visibility: selected
    selectedRepositories:
    - repoRef:
        name: sample-repository-ns
---
# An existing Dependabot secret available to all private repositories.
apiVersion: organizations.github.m.crossplane.io/v1alpha1
kind: DependabotSecretAccess
metadata:
  name: sample-dependabot-secret-private-ns
  namespace: default
  annotations:
    crossplane.io/external-name: SAMPLE_DEPENDABOT_SECRET_PRIVATE-ns
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: example
  forProvider:
    orgRef:
      name: pgh-sample-organization-ns
    visibility: private
