---
# Runner group available to all repositories in the organization.
apiVersion: organizations.github.m.crossplane.io/v1alpha1
kind: RunnerGroup
metadata:
  name: sample-runner-group-all-ns
  namespace: default
  annotations:
    crossplane.io/external-name: shared-runners-ns
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: example
  forProvider:
    orgRef:
      name: pgh-sample-organization-ns
    visibility: all
---
# Runner group available only to selected repositories and restricted
# to specific workflows.
apiVersion: organizations.github.m.crossplane.io/v1alpha1
kind: RunnerGroup
metadata:
  name: sample-runner-group-selected-ns
  namespace: default
  annotations:
    crossplane.io/external-name: deploy-runners-ns
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: example
  forProvider:
    orgRef:
      name: pgh-sample-organization-ns
    visibility: selected
    selectedRepositories:
    - repoRef:
        name: sample-repository-ns
    selectedWorkflows:
    - example-org/example-repo/.github/workflows/deploy.yml@refs/heads/main
