apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Team
metadata:
  name: sample-team
spec:
  forProvider:
    description: This is a sample team
    orgRef: 
      name: pgh-sample-organization
    members:
    - userRef:
        name: pgh-sample-user
      role: maintainer
    privacy: closed

---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Team
metadata:
  name: sample-sub-team
spec:
  forProvider:
    description: This is a sample team with a parent
    parentRef:
      name: sample-team
    orgRef: 
      name: pgh-sample-organization
    members:
    - userRef:
        name: pgh-sample-user
      role: maintainer
    privacy: closed
