#!/usr/bin/env bash
# test/migration/baseline.sh -- what makes the baseline (v0.22.0) state deterministic for the
# Repository fixtures that declare branch protection. Sourced by scenario.sh (the drivers) and by
# oob.sh (the GitHub calls); not executable on its own. Needs jq and yq; the orchestration also
# needs the helpers of scenario.sh and cluster.sh, the pure parts need nothing.
#
# The problem. A Repository created from a template repository is generated by GitHub
# ASYNCHRONOUSLY, and v0.22.0 reconciles the new repository within seconds. Which side of the
# generation its first Observe lands on decides the whole baseline:
#
#   * before the default branch exists: the branch is "not up to date", the Update applies the
#     declared protection (or fails 422 while the repository is still empty, and retries);
#   * after it, with the branch unprotected: v0.22.0 Observe errors "branch is not protected" and
#     never reaches Update, so the object stays Synced=False for good.
#
# A Synced=False object is dropped from the adoption, and with it every nested row it carries.
# So the harness does not leave this to the race: it waits for the generated default branch, and
# when v0.22.0 is stuck on the unprotected branch it seeds the protection the fixture declares
# through the GitHub API (the same kind of out-of-band seeding oob.sh does for the other
# preconditions) and waits for the object to become Synced. v0.22.0 is a tag and cannot change.
#
# shellcheck shell=bash

# The text v0.22.0 reports when it observes a branch that has no protection rule.
BASELINE_UNPROTECTED_TEXT="branch is not protected"

# Objects v0.22.0 cannot create at all: the only ones the adoption leaves out. An object that is
# not Synced for any other reason is a failure of the run, never an exclusion.
BASELINE_ALLOWED_EXCLUSIONS=("OrganizationVariable/pgh-mig-var-policies")

# baseline_is_allowed_exclusion <Kind/name>
baseline_is_allowed_exclusion() {
  local e
  for e in "${BASELINE_ALLOWED_EXCLUSIONS[@]}"; do
    [ "$1" != "${e}" ] || return 0
  done
  return 1
}

# ---------------------------------------------------------------------------
# Pure: what the fixtures declare, and the request that seeds it
# ---------------------------------------------------------------------------

# baseline_repo_docs <rendered-dir> -- every Repository of the rendered fixtures as one JSON
# document per line.
baseline_repo_docs() {
  local f
  for f in "$1"/*.yaml; do
    [ -e "${f}" ] || continue
    yq -o=json -I=0 '.' "${f}" | jq -c 'select(.kind == "Repository")'
  done
}

# baseline_protected_repos <rendered-dir> -- "<repository>\t<branch>" for every branch protection
# rule a Repository fixture declares.
baseline_protected_repos() {
  baseline_repo_docs "$1" | jq -r '
    .metadata.name as $n | (.spec.forProvider.branchProtectionRules // [])[] | [$n, .branch] | @tsv'
}

# baseline_repo_rule <rendered-dir> <repository> <branch> -- the rule of the fixture, as JSON, and
# the fixture's org: {"org": .., "rule": {..}, "permissions": {..}}.
baseline_repo_rule() {
  baseline_repo_docs "$1" | jq -c --arg n "$2" --arg b "$3" '
    select(.metadata.name == $n)
    | {org: .spec.forProvider.org, permissions: (.spec.forProvider.permissions // {}),
       rule: ((.spec.forProvider.branchProtectionRules // [])[] | select(.branch == $b))}'
}

# baseline_protection_body <rule-json> -- the body of PUT /repos/{o}/{r}/branches/{b}/protection
# for a branchProtectionRules entry. Signed commits have their own endpoint
# (baseline_wants_signatures).
baseline_protection_body() {
  jq -c '
    def lst: (. // []);
    {
      required_status_checks: (if .requiredStatusChecks == null then null else
        {strict: (.requiredStatusChecks.strict // false),
         checks: [(.requiredStatusChecks.checks | lst)[] | {context: .context} + (if .appId != null then {app_id: .appId} else {} end)]}
      end),
      enforce_admins: (.enforceAdmins // false),
      required_pull_request_reviews: (if .requiredPullRequestReviews == null then null else
        (.requiredPullRequestReviews as $r | {
          dismiss_stale_reviews: ($r.dismissStaleReviews // false),
          require_code_owner_reviews: ($r.requireCodeOwnerReviews // false),
          required_approving_review_count: ($r.requiredApprovingReviewCount // 0),
          require_last_push_approval: ($r.requireLastPushApproval // false)}
          + (if $r.bypassPullRequestAllowances == null then {} else
              {bypass_pull_request_allowances: {users: ($r.bypassPullRequestAllowances.users | lst), teams: ($r.bypassPullRequestAllowances.teams | lst), apps: ($r.bypassPullRequestAllowances.apps | lst)}} end)
          + (if $r.dismissalRestrictions == null then {} else
              {dismissal_restrictions: {users: ($r.dismissalRestrictions.users | lst), teams: ($r.dismissalRestrictions.teams | lst), apps: ($r.dismissalRestrictions.apps | lst)}} end))
      end),
      restrictions: (if .branchProtectionRestrictions == null then null else
        {users: (.branchProtectionRestrictions.users | lst), teams: (.branchProtectionRestrictions.teams | lst), apps: (.branchProtectionRestrictions.apps | lst)}
      end),
      required_linear_history: (.requireLinearHistory // false),
      allow_force_pushes: (.allowForcePushes // false),
      allow_deletions: (.allowDeletions // false),
      block_creations: (.branchProtectionRestrictions.blockCreations // false),
      required_conversation_resolution: (.requiredConversationResolution // false),
      lock_branch: (.lockBranch // false),
      allow_fork_syncing: (.allowForkSyncing // false)
    }'
}

# baseline_wants_signatures <rule-json> -- "true" when the rule requires signed commits.
baseline_wants_signatures() {
  jq -r '.requireSignedCommits // false'
}

# baseline_rule_actors <permissions-json> -- "team\t<slug>\t<role>" and "user\t<login>\t<role>" for
# the repository permissions the fixture declares: the principals a protection rule names must
# have push access to the repository before GitHub accepts the rule.
baseline_rule_actors() {
  jq -r '((.teams // [])[] | ["team", .team, .role] | @tsv), ((.users // [])[] | ["user", .user, .role] | @tsv)'
}

# baseline_protection_state <state.json> <Repository name> -- what v0.22.0 made of the object:
#   settled      Synced=True
#   unprotected  Synced=False because the branch has no protection rule (the deadlock)
#   pending      anything else (not reconciled yet, or failing for another reason)
baseline_protection_state() {
  jq -r --arg n "$2" --arg t "${BASELINE_UNPROTECTED_TEXT}" '
    [.[] | select(.kind == "Repository" and .name == $n)][0] as $o
    | if $o == null then "pending"
      elif $o.synced == "True" then "settled"
      elif ($o.synced == "False" and (($o.syncedMessage // "") | contains($t))) then "unprotected"
      else "pending" end' "$1" 2>/dev/null || echo pending
}

# ---------------------------------------------------------------------------
# Orchestration (used by the scenario drivers)
# ---------------------------------------------------------------------------

# baseline_oob <args...> -- the out-of-band tool; a function so that the self-test can stand in.
baseline_oob() { "${MIGRATION_DIR}/oob.sh" "$@"; }

BASELINE_SEEDED=""

# baseline_protection_step <rendered-dir> <group> -- one look at every Repository with declared
# protection: seeds the ones v0.22.0 is stuck on (once each), returns 0 when all are Synced.
baseline_protection_step() {
  local dir="$1" group="$2" state repo branch s pending=0
  state="$(mktemp)"
  mr_state "${group}" >"${state}"
  while IFS=$'\t' read -r repo branch; do
    [ -n "${repo}" ] || continue
    s="$(baseline_protection_state "${state}" "${repo}")"
    case "${s}" in
      settled) ;;
      unprotected)
        pending=1
        case " ${BASELINE_SEEDED} " in
          *" ${repo} "*) ;;
          *)
            if baseline_oob seed-protection "${dir}" "${repo}" >>"${EVIDENCE_DIR}/oob-seed.log" 2>&1; then
              BASELINE_SEEDED+=" ${repo}"
              record INFO "branch protection of ${repo} seeded out-of-band" \
                "v0.22.0 observed the generated default branch before it had a protection rule and reports '${BASELINE_UNPROTECTED_TEXT}' without ever reaching Update; the protection the fixture declares was applied through the GitHub API so the object can be Synced (a baseline limitation, see README)"
            else
              record FAIL "branch protection of ${repo} seeded out-of-band" "see oob-seed.log: $(tail -2 "${EVIDENCE_DIR}/oob-seed.log" | tr '\n' ' ')"
              rm -f "${state}"
              exit 1
            fi
            ;;
        esac
        ;;
      *) pending=1 ;;
    esac
  done < <(baseline_protected_repos "${dir}")
  rm -f "${state}"
  return "${pending}"
}

# baseline_settle_protected_repos <rendered-dir> <group> [timeout] -- called once the v1 fixtures
# are applied. For every Repository that declares branch protection: waits until GitHub has
# generated its default branch (no commits is a precondition failure, not a provider defect), then
# waits for v0.22.0 to make it Synced, seeding the protection when it is stuck on an unprotected
# branch. Returns 1 when an object is still not Synced at the timeout; the caller decides what that
# means.
baseline_settle_protected_repos() {
  local dir="$1" group="$2" timeout="${3:-${MIGRATION_SEED_TIMEOUT:-600}}" repo branch rc
  BASELINE_SEEDED=""
  [ -n "$(baseline_protected_repos "${dir}")" ] || return 0
  while IFS=$'\t' read -r repo branch; do
    [ -n "${repo}" ] || continue
    baseline_oob wait-branch "${repo}" "${branch}" "${timeout}" >>"${EVIDENCE_DIR}/oob-seed.log" 2>&1
    rc=$?
    case "${rc}" in
      0) log "${repo} has ${branch} with a commit" ;;
      3)
        record FAIL "the baseline created ${repo}" "the repository does not exist ${timeout}s after the fixtures were applied"
        exit 1
        ;;
      *)
        record FAIL "GitHub generated ${repo} from the template: ${branch} has a commit" \
          "GitHub did not generate ${repo} from the template: no commits (precondition, not a provider defect)"
        exit 1
        ;;
    esac
  done < <(baseline_protected_repos "${dir}")
  if wait_until "${timeout}" 10 baseline_protection_step "${dir}" "${group}"; then
    if [ -z "${BASELINE_SEEDED}" ]; then
      record INFO "the baseline applied the declared branch protection itself" "no out-of-band seeding was needed"
    fi
    return 0
  fi
  return 1
}
